#!/usr/bin/env python3
"""
parse_gpx.py — turn curated GPX route files into src/routes.js geometry.

Reads every *.gpx under raw/gpx/ and, for each, emits a frame-fit path
(x, y in 0..1, aspect-preserved, north up) plus a smoothed, self-scaled
elevation profile — keyed by Garmin activity id. Distance and climb are
computed here so the figures are honest.

Authored labels (trail names, notes, race context) live in content.js; this
script only produces geometry, so a route regenerates cleanly if its GPX is
re-exported. Keep the GPX files in raw/gpx/ (gitignored) for that.

Run:  python3 tools/parse_gpx.py
Emits: src/routes.js  (AUTO-GENERATED — do not hand-edit)
"""
import glob, os, re, json, xml.etree.ElementTree as ET
from math import radians, sin, cos, asin, sqrt

NS = "{http://www.topografix.com/GPX/1/1}"
GPX_DIR = os.path.join(os.path.dirname(__file__), "..", "raw", "gpx")
OUT = os.path.join(os.path.dirname(__file__), "..", "src", "routes.js")

PATH_POINTS = 160   # simplified track points per route
ELE_POINTS = 120    # elevation profile samples
SMOOTH_WIN = 25     # moving-average window over raw ele points (kills baro drift)


def haversine_m(lat1, lon1, lat2, lon2):
    r = 6371000.0
    dlat, dlon = radians(lat2 - lat1), radians(lon2 - lon1)
    a = sin(dlat / 2) ** 2 + cos(radians(lat1)) * cos(radians(lat2)) * sin(dlon / 2) ** 2
    return 2 * r * asin(sqrt(a))


def load(f):
    root = ET.parse(f).getroot()
    pts = []
    for tp in root.iter(NS + "trkpt"):
        lat, lon = float(tp.get("lat")), float(tp.get("lon"))
        ee = tp.find(NS + "ele")
        pts.append((lat, lon, float(ee.text) if ee is not None else None))
    return pts


def downsample(seq, target):
    if len(seq) <= target:
        return seq
    step = len(seq) / target
    return [seq[int(i * step)] for i in range(target)] + [seq[-1]]


def fit_path(pts):
    """cos-lat corrected, fit to [0,1] preserving aspect, centered, north up."""
    mlat = sum(p[0] for p in pts) / len(pts)
    k = cos(radians(mlat))
    xs = [p[1] * k for p in pts]
    ys = [p[0] for p in pts]
    xmin, xmax, ymin, ymax = min(xs), max(xs), min(ys), max(ys)
    w, h = (xmax - xmin) or 1e-9, (ymax - ymin) or 1e-9
    s = 1.0 / max(w, h)
    offx, offy = (1 - w * s) / 2, (1 - h * s) / 2
    return [[round(offx + (x - xmin) * s, 4), round(offy + (ymax - y) * s, 4)] for x, y in zip(xs, ys)]


def smooth(eles):
    ev = [e for e in eles if e is not None]
    if not ev:
        return []
    out = []
    half = SMOOTH_WIN // 2
    for i in range(len(ev)):
        lo, hi = max(0, i - half), min(len(ev), i + half + 1)
        out.append(sum(ev[lo:hi]) / (hi - lo))
    return out


def main():
    files = sorted(glob.glob(os.path.join(GPX_DIR, "*.gpx")))
    if not files:
        raise SystemExit(f"No .gpx files under {GPX_DIR}. Drop the curated route GPX there and re-run.")
    routes = {}
    for f in files:
        aid = re.search(r"(\d+)", os.path.basename(f)).group(1)
        pts = load(f)
        if len(pts) < 2:
            continue
        dist_m = sum(haversine_m(pts[i - 1][0], pts[i - 1][1], pts[i][0], pts[i][1]) for i in range(1, len(pts)))
        path = fit_path(downsample(pts, PATH_POINTS))
        sm = smooth([p[2] for p in pts])
        if sm:
            emin, emax = min(sm), max(sm)
            gain_m = sum(max(0, sm[i] - sm[i - 1]) for i in range(1, len(sm)))
            prof = downsample(sm, ELE_POINTS)
            ele = [round((e - emin) / (emax - emin), 3) if emax > emin else 0.0 for e in prof]
        else:
            emin = emax = gain_m = 0
            ele = []
        routes[aid] = {
            "mi": round(dist_m / 1609.344, 2),
            "gainFt": round(gain_m * 3.28084),
            "path": path,
            "ele": ele,
        }
    with open(OUT, "w") as fo:
        fo.write("// AUTO-GENERATED by tools/parse_gpx.py — do not hand-edit.\n")
        fo.write("// Frame-fit path (x,y in 0..1, north up) + self-scaled elevation, per activity id.\n")
        fo.write("// Regenerate: python3 tools/parse_gpx.py  (reads raw/gpx/*.gpx)\n\n")
        fo.write("export const ROUTES = " + json.dumps(routes, separators=(",", ":")) + ";\n")
    print(f"Wrote {OUT} with {len(routes)} routes")
    for aid, r in sorted(routes.items(), key=lambda x: -x[1]["mi"]):
        print(f"  {aid:>13}  {r['mi']:6.2f} mi  +{r['gainFt']:>5} ft  {len(r['path'])} pts")


if __name__ == "__main__":
    main()
