// AUTHORED CONTENT — Remi's voice and curated race records.
// Safe to hand-edit. NOT touched by tools/build_data.py.

export const CONTENT = {
  featured: [
    {
      id:"asheville",title:"Asheville Marathon",subtitle:"Sub-3:00 · BQ · 3rd Masters",
      date:"March 21, 2026",location:"Asheville, NC",distance:"26.30 mi (42.3 km)",
      time:"2:59:27",pace:"6:49/mi",elev:"+941 / −1,161 ft (net downhill)",hr:"167 avg / 188 max",
      cadence:"85 spm",stride:"1.38 m",steps:"30,504",calories:"10,911",
      te:"5.0 aer / 2.1 anaer",vo2:"65",maxPace:"6:00/mi",
      photo:"https://remikalir.com/wp-content/uploads/2026/03/remi_ashevillemarathon_portfolio3-scaled.jpg",
      photoCaption:"Enjoying downtown Asheville on my way to a 2:59:27 finish",
      hrZones:[{z:"Zone 1–3",min:3.9,pct:2},{z:"Zone 4",min:31.3,pct:17},{z:"Zone 5",min:141.1,pct:79},{z:"Zone 6",min:3.1,pct:2}],
      segments:[],
      training:[{w:"-6",r:7,mi:31},{w:"-5",r:7,mi:35},{w:"-4",r:7,mi:46},{w:"-3",r:7,mi:44},{w:"-2",r:7,mi:32},{w:"-1",r:4,mi:19}],
      goals:["Break 3:00:00","Boston Marathon qualifier","Masters Division podium"],
      results:["2:59:27 — sub-3 by 33 seconds","BQ time achieved (qualifying standard: 3:25:00)","3rd place, Masters Division"],
      narrative:"The goal was sub-3:00 and I cleared it with 33 seconds to spare — also qualifying for Boston and placing third in the Masters Division. This was my marathon debut, built on a foundation of ultra training including a Frosty 50 in January (31.4 mi at 7:39/mi) and months of volume. The Asheville course is net downhill (−220 ft) but features punchy climbs totaling 941 ft of gain. I ran the entire race at threshold — 79% of the time in HR zone 5, peaking at 188 bpm. The 6:49/mi average was remarkably even. The last long run — a 21-miler at 6:52/mi — came 20 days before, and race week was a classic taper to 19 miles.",
    },
    {
      id:"fonta-flora",title:"Fonta Flora 50K",subtitle:"First ultramarathon · Sub-5:00",
      date:"October 25, 2025",location:"Burke County, NC",distance:"32.38 mi (52.1 km)",
      time:"4:48:12",pace:"8:54/mi",elev:"+3,523 ft (1,074 m)",hr:"157 avg / 176 max",
      cadence:"81 spm",stride:"1.11 m",steps:"46,886",calories:"15,516",
      te:"5.0 aerobic",vo2:"66",maxPace:"6:50/mi",
      photo:"https://remikalir.com/wp-content/uploads/2026/03/remi_fontaflora_portfolio1-scaled.jpeg",
      photoCaption:"On the Fonta Flora trail in the Blue Ridge foothills",
      hrZones:[{z:"Zone 1–2",min:5.2,pct:2},{z:"Zone 3",min:17.6,pct:6},{z:"Zone 4",min:152.6,pct:53},{z:"Zone 5",min:112.8,pct:39}],
      segments:[
        {n:1,mi:9.4,min:85,pace:"9:01",note:"Controlled start through rolling hills"},
        {n:2,mi:4.9,min:40,pace:"8:01",note:"Fastest segment — found a rhythm"},
        {n:3,mi:6.7,min:55,pace:"8:13",note:"Holding steady through the middle"},
        {n:4,mi:5.7,min:47,pace:"8:11",note:"Last comfortable segment"},
        {n:5,mi:2.2,min:21,pace:"9:36",note:"Fatigue sets in, pace drops"},
        {n:6,mi:1.8,min:18,pace:"10:10",note:"Grinding through the final miles"},
        {n:7,mi:0.6,min:6,pace:"9:48",note:"Short rolling segment"},
        {n:8,mi:0.8,min:8,pace:"10:04",note:"Push to the finish"},
      ],
      training:[{w:"-6",r:5,mi:41},{w:"-5",r:5,mi:35},{w:"-4",r:6,mi:45},{w:"-3",r:6,mi:44},{w:"-2",r:5,mi:33},{w:"-1",r:4,mi:19}],
      goals:["Finish first ultramarathon","Break 5:00:00"],
      results:["Finished in 4:48:12 — sub-5 by nearly 12 minutes","32.38 miles with 3,523 ft of climbing on trail"],
      narrative:"My first ultra — 50 kilometers through the Blue Ridge foothills on the Fonta Flora trail. The course featured relentless rolling terrain with 3,523 ft of climbing across 10 aid-station segments. I went out conservatively, holding 8:00–8:13/mi through the first four segments (26.8 miles), then slowed to 9:36–10:10/mi as fatigue set in over the final 5.6 miles. Heart rate stayed high — 92% of the race in zones 4–5 — and cadence dropped from 84 to 82 spm as stride shortened. The 6-week build peaked at 45 miles in week -4, tapering to 19 miles race week. Nearly 47,000 steps and 15,500 calories — the biggest day in the dataset by a wide margin.",
    },
    {
      id:"mistletoe",title:"2024 Mistletoe Run",subtitle:"Half marathon PR · 1st Masters · 8th overall",
      date:"December 7, 2024",location:"Winston-Salem, NC",distance:"13.23 mi (21.3 km)",
      time:"1:18:55",pace:"5:57/mi",elev:"+492 ft",hr:"N/A (sensor issue)",
      cadence:"88 spm",stride:"1.52 m",steps:"13,938",calories:"5,560",
      te:"2.2 aerobic",vo2:"—",maxPace:"5:12/mi",
      hrZones:[],segments:[],
      training:[{w:"-6",r:7,mi:47},{w:"-5",r:7,mi:37},{w:"-4",r:7,mi:42},{w:"-3",r:5,mi:42},{w:"-2",r:2,mi:12},{w:"-1",r:3,mi:22}],
      goals:["Win Masters Division","Target sub-1:20"],
      results:["1:18:55 — half marathon PR by 6 seconds","1st place, Masters Division","8th place overall"],
      prContext:[
        {date:"2024-12-07",time:"1:18:55",pace:"5:57",loc:"Winston-Salem",pr:true},
        {date:"2022-10-30",time:"1:19:01",pace:"6:01",loc:"Cambridge"},
        {date:"2022-10-16",time:"1:19:58",pace:"6:06",loc:"Cambridge"},
        {date:"2022-11-13",time:"1:20:35",pace:"6:05",loc:"Boston"},
        {date:"2021-02-28",time:"1:20:51",pace:"6:12",loc:"Denver"},
      ],
      narrative:"After 31 half-marathon-distance runs across 7 years, I broke through the 1:19 barrier at the Mistletoe Run in Winston-Salem — winning the Masters Division and placing 8th overall. The 5:57/mi average was my fastest ever over 13+ miles, 6 seconds quicker than my previous best set in Cambridge two years earlier. Biomechanics were dialed: 88 spm cadence and a 1.52 m stride, both distance bests. The course has moderate hills (492 ft gain), and cool December conditions were ideal. A sharp taper — 47 miles six weeks out, dropping to just 12 miles two weeks before — left me fresh.",
    },
    {
      id:"salem-lake",title:"Salem Lake 30K",subtitle:"3rd place overall",
      date:"September 28, 2024",location:"Winston-Salem, NC",distance:"18.90 mi (30.4 km)",
      time:"2:02:03",pace:"6:27/mi",elev:"+1,686 ft",hr:"156 avg / 174 max",
      cadence:"85 spm",stride:"1.45 m",steps:"20,920",calories:"7,684",
      te:"5.0 aerobic",vo2:"69",maxPace:"5:24/mi",
      hrZones:[],segments:[],
      training:[{w:"-6",r:5,mi:35},{w:"-5",r:6,mi:45},{w:"-4",r:7,mi:44},{w:"-3",r:7,mi:35},{w:"-2",r:5,mi:39},{w:"-1",r:4,mi:31}],
      goals:["Complete first Salem Lake 30K","Compete for a podium finish"],
      results:["2:02:03 finish time","3rd place overall","VO2 max reading of 69 — season peak"],
      narrative:"My first Salem Lake 30K — a hilly loop course around Salem Lake in Winston-Salem with 1,686 ft of climbing over 18.9 miles. I came in third place overall at a 6:27/mi pace, which at the time was my fastest effort at any distance beyond a half marathon. The course is demanding — the elevation profile never lets up — and my max pace hit 5:24/mi on the downhills. Heart rate averaged 156 with a max of 174, and Garmin recorded a VO2 max of 69, my peak for the year. This race marked the beginning of my move into longer distances, setting the stage for the Fonta Flora 50K and the Asheville Marathon that followed.",
    },
  ],
  photos: {
    frosty: "https://remikalir.com/wp-content/uploads/2026/03/remi_frosty50_portfolio2-scaled.jpg",
  },
  homeNotes: {
    "Denver, CO": "7 years at altitude, City Park loops",
    "Cambridge, MA": "11 months along the Charles",
    "Winston-Salem, NC": "Ultra & marathon training base"
  },
};
