// AUTO-GENERATED by tools/build_data.py — do not hand-edit.
// Regenerate after a new Garmin export: python3 tools/build_data.py
// Generated 2026-07-28 from export through 2026-06-20.

export const DATA = {
  "summary": {
    "totalRuns": 2362,
    "totalMiles": 17603,
    "totalHours": 1911,
    "pr5k": "16:53",
    "prHalf": "1:18:55",
    "prMarathon": "2:59:27",
    "prMile": "5:20",
    "vo2": 64,
    "avgPerWeek": 4.8,
    "countries": 4,
    "usStates": 17,
    "cities": 42
  },
  "yearly": [
    {
      "year": 2016,
      "runs": 2,
      "miles": 11,
      "pace": "6:45",
      "paceN": 6.75
    },
    {
      "year": 2017,
      "runs": 215,
      "miles": 1669,
      "pace": "6:31",
      "paceN": 6.52
    },
    {
      "year": 2018,
      "runs": 239,
      "miles": 1925,
      "pace": "6:19",
      "paceN": 6.32
    },
    {
      "year": 2019,
      "runs": 226,
      "miles": 1684,
      "pace": "6:18",
      "paceN": 6.3
    },
    {
      "year": 2020,
      "runs": 207,
      "miles": 1641,
      "pace": "6:15",
      "paceN": 6.25
    },
    {
      "year": 2021,
      "runs": 288,
      "miles": 1938,
      "pace": "6:21",
      "paceN": 6.35
    },
    {
      "year": 2022,
      "runs": 299,
      "miles": 1944,
      "pace": "6:38",
      "paceN": 6.64
    },
    {
      "year": 2023,
      "runs": 231,
      "miles": 1924,
      "pace": "6:22",
      "paceN": 6.36
    },
    {
      "year": 2024,
      "runs": 260,
      "miles": 1887,
      "pace": "6:32",
      "paceN": 6.53
    },
    {
      "year": 2025,
      "runs": 263,
      "miles": 2035,
      "pace": "6:58",
      "paceN": 6.97
    },
    {
      "year": 2026,
      "runs": 132,
      "miles": 947,
      "pace": "7:06",
      "paceN": 7.1
    }
  ],
  "monthly": [
    {
      "m": "2016-12",
      "mi": 11
    },
    {
      "m": "2017-01",
      "mi": 12
    },
    {
      "m": "2017-02",
      "mi": 99
    },
    {
      "m": "2017-03",
      "mi": 146
    },
    {
      "m": "2017-04",
      "mi": 129
    },
    {
      "m": "2017-05",
      "mi": 151
    },
    {
      "m": "2017-06",
      "mi": 161
    },
    {
      "m": "2017-07",
      "mi": 155
    },
    {
      "m": "2017-08",
      "mi": 165
    },
    {
      "m": "2017-09",
      "mi": 149
    },
    {
      "m": "2017-10",
      "mi": 159
    },
    {
      "m": "2017-11",
      "mi": 170
    },
    {
      "m": "2017-12",
      "mi": 173
    },
    {
      "m": "2018-01",
      "mi": 173
    },
    {
      "m": "2018-02",
      "mi": 128
    },
    {
      "m": "2018-03",
      "mi": 167
    },
    {
      "m": "2018-04",
      "mi": 151
    },
    {
      "m": "2018-05",
      "mi": 177
    },
    {
      "m": "2018-06",
      "mi": 162
    },
    {
      "m": "2018-07",
      "mi": 183
    },
    {
      "m": "2018-08",
      "mi": 187
    },
    {
      "m": "2018-09",
      "mi": 166
    },
    {
      "m": "2018-10",
      "mi": 169
    },
    {
      "m": "2018-11",
      "mi": 159
    },
    {
      "m": "2018-12",
      "mi": 101
    },
    {
      "m": "2019-01",
      "mi": 129
    },
    {
      "m": "2019-02",
      "mi": 126
    },
    {
      "m": "2019-03",
      "mi": 149
    },
    {
      "m": "2019-04",
      "mi": 163
    },
    {
      "m": "2019-05",
      "mi": 169
    },
    {
      "m": "2019-06",
      "mi": 165
    },
    {
      "m": "2019-07",
      "mi": 178
    },
    {
      "m": "2019-08",
      "mi": 148
    },
    {
      "m": "2019-09",
      "mi": 73
    },
    {
      "m": "2019-10",
      "mi": 94
    },
    {
      "m": "2019-11",
      "mi": 151
    },
    {
      "m": "2019-12",
      "mi": 141
    },
    {
      "m": "2020-01",
      "mi": 155
    },
    {
      "m": "2020-02",
      "mi": 123
    },
    {
      "m": "2020-03",
      "mi": 144
    },
    {
      "m": "2020-04",
      "mi": 147
    },
    {
      "m": "2020-05",
      "mi": 168
    },
    {
      "m": "2020-06",
      "mi": 157
    },
    {
      "m": "2020-07",
      "mi": 179
    },
    {
      "m": "2020-08",
      "mi": 151
    },
    {
      "m": "2020-09",
      "mi": 134
    },
    {
      "m": "2020-10",
      "mi": 157
    },
    {
      "m": "2020-11",
      "mi": 125
    },
    {
      "m": "2021-01",
      "mi": 79
    },
    {
      "m": "2021-02",
      "mi": 155
    },
    {
      "m": "2021-03",
      "mi": 161
    },
    {
      "m": "2021-04",
      "mi": 178
    },
    {
      "m": "2021-05",
      "mi": 175
    },
    {
      "m": "2021-06",
      "mi": 161
    },
    {
      "m": "2021-07",
      "mi": 175
    },
    {
      "m": "2021-08",
      "mi": 176
    },
    {
      "m": "2021-09",
      "mi": 170
    },
    {
      "m": "2021-10",
      "mi": 183
    },
    {
      "m": "2021-11",
      "mi": 173
    },
    {
      "m": "2021-12",
      "mi": 152
    },
    {
      "m": "2022-01",
      "mi": 162
    },
    {
      "m": "2022-02",
      "mi": 65
    },
    {
      "m": "2022-03",
      "mi": 154
    },
    {
      "m": "2022-04",
      "mi": 155
    },
    {
      "m": "2022-05",
      "mi": 173
    },
    {
      "m": "2022-06",
      "mi": 160
    },
    {
      "m": "2022-07",
      "mi": 166
    },
    {
      "m": "2022-08",
      "mi": 170
    },
    {
      "m": "2022-09",
      "mi": 180
    },
    {
      "m": "2022-10",
      "mi": 201
    },
    {
      "m": "2022-11",
      "mi": 184
    },
    {
      "m": "2022-12",
      "mi": 175
    },
    {
      "m": "2023-01",
      "mi": 193
    },
    {
      "m": "2023-02",
      "mi": 170
    },
    {
      "m": "2023-03",
      "mi": 190
    },
    {
      "m": "2023-04",
      "mi": 172
    },
    {
      "m": "2023-05",
      "mi": 194
    },
    {
      "m": "2023-06",
      "mi": 164
    },
    {
      "m": "2023-07",
      "mi": 110
    },
    {
      "m": "2023-08",
      "mi": 188
    },
    {
      "m": "2023-09",
      "mi": 165
    },
    {
      "m": "2023-10",
      "mi": 180
    },
    {
      "m": "2023-11",
      "mi": 167
    },
    {
      "m": "2023-12",
      "mi": 30
    },
    {
      "m": "2024-01",
      "mi": 89
    },
    {
      "m": "2024-02",
      "mi": 143
    },
    {
      "m": "2024-03",
      "mi": 181
    },
    {
      "m": "2024-04",
      "mi": 140
    },
    {
      "m": "2024-05",
      "mi": 187
    },
    {
      "m": "2024-06",
      "mi": 163
    },
    {
      "m": "2024-07",
      "mi": 170
    },
    {
      "m": "2024-08",
      "mi": 180
    },
    {
      "m": "2024-09",
      "mi": 161
    },
    {
      "m": "2024-10",
      "mi": 183
    },
    {
      "m": "2024-11",
      "mi": 134
    },
    {
      "m": "2024-12",
      "mi": 156
    },
    {
      "m": "2025-01",
      "mi": 163
    },
    {
      "m": "2025-02",
      "mi": 161
    },
    {
      "m": "2025-03",
      "mi": 169
    },
    {
      "m": "2025-04",
      "mi": 176
    },
    {
      "m": "2025-05",
      "mi": 180
    },
    {
      "m": "2025-06",
      "mi": 167
    },
    {
      "m": "2025-07",
      "mi": 179
    },
    {
      "m": "2025-08",
      "mi": 173
    },
    {
      "m": "2025-09",
      "mi": 173
    },
    {
      "m": "2025-10",
      "mi": 157
    },
    {
      "m": "2025-11",
      "mi": 173
    },
    {
      "m": "2025-12",
      "mi": 164
    },
    {
      "m": "2026-01",
      "mi": 172
    },
    {
      "m": "2026-02",
      "mi": 151
    },
    {
      "m": "2026-03",
      "mi": 152
    },
    {
      "m": "2026-04",
      "mi": 176
    },
    {
      "m": "2026-05",
      "mi": 184
    },
    {
      "m": "2026-06",
      "mi": 112
    }
  ],
  "paces": [
    {
      "p": "5:00",
      "c": 1
    },
    {
      "p": "5:15",
      "c": 2
    },
    {
      "p": "5:30",
      "c": 13
    },
    {
      "p": "5:45",
      "c": 130
    },
    {
      "p": "6:00",
      "c": 506
    },
    {
      "p": "6:15",
      "c": 639
    },
    {
      "p": "6:30",
      "c": 419
    },
    {
      "p": "6:45",
      "c": 277
    },
    {
      "p": "7:00",
      "c": 109
    },
    {
      "p": "7:15",
      "c": 60
    },
    {
      "p": "7:30",
      "c": 35
    },
    {
      "p": "7:45",
      "c": 39
    },
    {
      "p": "8:00",
      "c": 30
    },
    {
      "p": "8:15",
      "c": 38
    },
    {
      "p": "8:30",
      "c": 14
    },
    {
      "p": "8:45",
      "c": 19
    },
    {
      "p": "9:00",
      "c": 10
    },
    {
      "p": "9:15",
      "c": 9
    },
    {
      "p": "9:30",
      "c": 1
    },
    {
      "p": "9:45",
      "c": 1
    },
    {
      "p": "10:00+",
      "c": 10
    }
  ],
  "paceByYear": [
    {
      "year": 2016,
      "c": [
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ]
    },
    {
      "year": 2017,
      "c": [
        0,
        0,
        0,
        0,
        23,
        97,
        55,
        30,
        2,
        2,
        1,
        1,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        3
      ]
    },
    {
      "year": 2018,
      "c": [
        0,
        0,
        0,
        7,
        92,
        77,
        51,
        5,
        2,
        1,
        0,
        1,
        0,
        0,
        0,
        0,
        2,
        1,
        0,
        0,
        0
      ]
    },
    {
      "year": 2019,
      "c": [
        0,
        0,
        0,
        28,
        67,
        85,
        25,
        8,
        8,
        3,
        1,
        0,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        0,
        0
      ]
    },
    {
      "year": 2020,
      "c": [
        0,
        0,
        1,
        28,
        76,
        57,
        23,
        11,
        6,
        4,
        0,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ]
    },
    {
      "year": 2021,
      "c": [
        0,
        0,
        0,
        25,
        71,
        64,
        55,
        50,
        14,
        6,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        2,
        0,
        0,
        0
      ]
    },
    {
      "year": 2022,
      "c": [
        0,
        0,
        0,
        5,
        32,
        55,
        55,
        63,
        45,
        20,
        7,
        7,
        4,
        4,
        1,
        1,
        0,
        0,
        0,
        0,
        0
      ]
    },
    {
      "year": 2023,
      "c": [
        0,
        0,
        0,
        19,
        60,
        67,
        53,
        24,
        2,
        2,
        0,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        3
      ]
    },
    {
      "year": 2024,
      "c": [
        1,
        1,
        5,
        3,
        48,
        78,
        46,
        43,
        8,
        6,
        3,
        4,
        4,
        2,
        0,
        3,
        1,
        2,
        0,
        0,
        2
      ]
    },
    {
      "year": 2025,
      "c": [
        0,
        0,
        0,
        15,
        30,
        43,
        42,
        33,
        18,
        9,
        5,
        9,
        7,
        16,
        8,
        14,
        7,
        4,
        1,
        1,
        1
      ]
    },
    {
      "year": 2026,
      "c": [
        0,
        1,
        7,
        0,
        7,
        16,
        13,
        9,
        4,
        7,
        17,
        15,
        14,
        16,
        5,
        0,
        0,
        0,
        0,
        0,
        1
      ]
    }
  ],
  "weekday": [
    {
      "d": "Mon",
      "r": 43,
      "mi": 249
    },
    {
      "d": "Tue",
      "r": 483,
      "mi": 3321
    },
    {
      "d": "Wed",
      "r": 429,
      "mi": 2678
    },
    {
      "d": "Thu",
      "r": 395,
      "mi": 2190
    },
    {
      "d": "Fri",
      "r": 402,
      "mi": 3512
    },
    {
      "d": "Sat",
      "r": 168,
      "mi": 893
    },
    {
      "d": "Sun",
      "r": 442,
      "mi": 4760
    }
  ],
  "vo2": [
    {
      "d": "2023-07",
      "v": 65.0
    },
    {
      "d": "2023-10",
      "v": 62.0
    },
    {
      "d": "2024-01",
      "v": 67.0
    },
    {
      "d": "2024-04",
      "v": 67.0
    },
    {
      "d": "2024-07",
      "v": 69.0
    },
    {
      "d": "2024-10",
      "v": 68.0
    },
    {
      "d": "2025-01",
      "v": 67.0
    },
    {
      "d": "2025-04",
      "v": 68.0
    },
    {
      "d": "2025-07",
      "v": 66.0
    },
    {
      "d": "2025-10",
      "v": 65.0
    },
    {
      "d": "2026-01",
      "v": 65.0
    },
    {
      "d": "2026-04",
      "v": 64.0
    }
  ],
  "bio": [
    {
      "y": 2016,
      "c": 84.0,
      "s": 1.4
    },
    {
      "y": 2017,
      "c": 83.8,
      "s": 1.45
    },
    {
      "y": 2018,
      "c": 84.8,
      "s": 1.48
    },
    {
      "y": 2019,
      "c": 86.5,
      "s": 1.46
    },
    {
      "y": 2020,
      "c": 86.3,
      "s": 1.47
    },
    {
      "y": 2021,
      "c": 86.3,
      "s": 1.43
    },
    {
      "y": 2022,
      "c": 85.5,
      "s": 1.38
    },
    {
      "y": 2023,
      "c": 87.6,
      "s": 1.42
    },
    {
      "y": 2024,
      "c": 86.1,
      "s": 1.41
    },
    {
      "y": 2025,
      "c": 84.7,
      "s": 1.35
    },
    {
      "y": 2026,
      "c": 84.8,
      "s": 1.31
    }
  ],
  "homes": [
    {
      "name": "Denver, CO",
      "dates": "2016\u20132024",
      "runs": 1471,
      "miles": 10781,
      "pace": "6:21",
      "lat": 39.7507,
      "lng": -104.9644
    },
    {
      "name": "Cambridge, MA",
      "dates": "Aug 2022\u2013Jun 2023",
      "runs": 222,
      "miles": 1865,
      "pace": "6:23",
      "lat": 42.3742,
      "lng": -71.1075
    },
    {
      "name": "Winston-Salem, NC",
      "dates": "Jul 2024\u2013present",
      "runs": 426,
      "miles": 3241,
      "pace": "6:52",
      "lat": 36.1082,
      "lng": -80.26
    }
  ],
  "locations": [
    {
      "name": "Denver",
      "runs": 1471,
      "mi": 10781
    },
    {
      "name": "Winston-Salem",
      "runs": 426,
      "mi": 3241
    },
    {
      "name": "Cambridge",
      "runs": 224,
      "mi": 1881
    },
    {
      "name": "Altadena/Pasadena",
      "runs": 47,
      "mi": 338
    },
    {
      "name": "Camden-Wyoming",
      "runs": 7,
      "mi": 58
    },
    {
      "name": "Littleton",
      "runs": 5,
      "mi": 29
    },
    {
      "name": "Chicago",
      "runs": 3,
      "mi": 28
    },
    {
      "name": "New York",
      "runs": 3,
      "mi": 29
    },
    {
      "name": "Vancouver",
      "runs": 3,
      "mi": 28
    },
    {
      "name": "El Cerrito",
      "runs": 3,
      "mi": 25
    },
    {
      "name": "San Francisco",
      "runs": 3,
      "mi": 20
    },
    {
      "name": "Dublin",
      "runs": 3,
      "mi": 23
    },
    {
      "name": "Nashville",
      "runs": 3,
      "mi": 17
    },
    {
      "name": "Ann Arbor",
      "runs": 3,
      "mi": 26
    },
    {
      "name": "Toronto",
      "runs": 3,
      "mi": 24
    }
  ],
  "geo": [
    {
      "name": "Denver",
      "runs": 1471,
      "mi": 10781,
      "country": "United States",
      "lat": 39.7507,
      "lng": -104.9644
    },
    {
      "name": "Winston-Salem",
      "runs": 426,
      "mi": 3241,
      "country": "United States",
      "lat": 36.1082,
      "lng": -80.26
    },
    {
      "name": "Cambridge",
      "runs": 224,
      "mi": 1881,
      "country": "United States",
      "lat": 42.3741,
      "lng": -71.1074
    },
    {
      "name": "Altadena/Pasadena",
      "runs": 47,
      "mi": 338,
      "country": "United States",
      "lat": 34.1723,
      "lng": -118.1108
    },
    {
      "name": "Camden-Wyoming",
      "runs": 7,
      "mi": 58,
      "country": "United States",
      "lat": 39.1002,
      "lng": -75.565
    },
    {
      "name": "Littleton",
      "runs": 5,
      "mi": 29,
      "country": "United States",
      "lat": 39.5937,
      "lng": -105.0097
    },
    {
      "name": "Chicago",
      "runs": 3,
      "mi": 28,
      "country": "United States",
      "lat": 41.8945,
      "lng": -87.6586
    },
    {
      "name": "New York",
      "runs": 3,
      "mi": 29,
      "country": "United States",
      "lat": 40.7665,
      "lng": -73.9731
    },
    {
      "name": "Vancouver",
      "runs": 3,
      "mi": 28,
      "country": "Canada",
      "lat": 49.2772,
      "lng": -123.2087
    },
    {
      "name": "El Cerrito",
      "runs": 3,
      "mi": 25,
      "country": "United States",
      "lat": 37.9037,
      "lng": -122.2991
    },
    {
      "name": "San Francisco",
      "runs": 3,
      "mi": 20,
      "country": "United States",
      "lat": 37.7905,
      "lng": -122.438
    },
    {
      "name": "Dublin",
      "runs": 3,
      "mi": 23,
      "country": "Ireland",
      "lat": 53.3308,
      "lng": -6.2838
    },
    {
      "name": "Nashville",
      "runs": 3,
      "mi": 17,
      "country": "United States",
      "lat": 36.1437,
      "lng": -86.797
    },
    {
      "name": "Ann Arbor",
      "runs": 3,
      "mi": 26,
      "country": "United States",
      "lat": 42.2931,
      "lng": -83.7415
    },
    {
      "name": "Toronto",
      "runs": 3,
      "mi": 24,
      "country": "Canada",
      "lat": 43.6886,
      "lng": -79.4378
    },
    {
      "name": "San Diego",
      "runs": 3,
      "mi": 19,
      "country": "United States",
      "lat": 32.7216,
      "lng": -117.1639
    },
    {
      "name": "Ocean City",
      "runs": 3,
      "mi": 18,
      "country": "United States",
      "lat": 38.3984,
      "lng": -75.0606
    },
    {
      "name": "Boston",
      "runs": 3,
      "mi": 15,
      "country": "United States",
      "lat": 42.3477,
      "lng": -71.1125
    },
    {
      "name": "Galway",
      "runs": 2,
      "mi": 19,
      "country": "Ireland",
      "lat": 53.2883,
      "lng": -9.0321
    },
    {
      "name": "St Louis",
      "runs": 2,
      "mi": 20,
      "country": "United States",
      "lat": 38.609,
      "lng": -90.2036
    },
    {
      "name": "Sachuest Point",
      "runs": 2,
      "mi": 19,
      "country": "United States",
      "lat": 41.4921,
      "lng": -71.2778
    },
    {
      "name": "Suzhou",
      "runs": 2,
      "mi": 10,
      "country": "China",
      "lat": 31.4177,
      "lng": 120.8914
    },
    {
      "name": "Annapolis",
      "runs": 2,
      "mi": 13,
      "country": "United States",
      "lat": 38.9784,
      "lng": -76.4914
    },
    {
      "name": "Boulder",
      "runs": 1,
      "mi": 9,
      "country": "United States",
      "lat": 40.0075,
      "lng": -105.3346
    },
    {
      "name": "Troy",
      "runs": 1,
      "mi": 10,
      "country": "United States",
      "lat": 42.7835,
      "lng": -73.6742
    },
    {
      "name": "Rollinsville",
      "runs": 1,
      "mi": 0,
      "country": "United States",
      "lat": 39.8508,
      "lng": -105.6884
    },
    {
      "name": "Albuquerque",
      "runs": 1,
      "mi": 7,
      "country": "United States",
      "lat": 35.1781,
      "lng": -106.6558
    },
    {
      "name": "Fredericksburg",
      "runs": 1,
      "mi": 9,
      "country": "United States",
      "lat": 38.3006,
      "lng": -77.4582
    },
    {
      "name": "Garden Grove",
      "runs": 1,
      "mi": 9,
      "country": "United States",
      "lat": 33.7887,
      "lng": -117.9152
    },
    {
      "name": "Sheridan",
      "runs": 1,
      "mi": 11,
      "country": "United States",
      "lat": 39.6318,
      "lng": -105.0159
    },
    {
      "name": "Niagara Falls",
      "runs": 1,
      "mi": 8,
      "country": "Canada",
      "lat": 43.0863,
      "lng": -79.0589
    },
    {
      "name": "Cherry Hills Village",
      "runs": 1,
      "mi": 11,
      "country": "United States",
      "lat": 39.6385,
      "lng": -104.9394
    },
    {
      "name": "Pottstown",
      "runs": 1,
      "mi": 6,
      "country": "United States",
      "lat": 40.2458,
      "lng": -75.6321
    },
    {
      "name": "Aurora",
      "runs": 1,
      "mi": 10,
      "country": "United States",
      "lat": 39.814,
      "lng": -104.753
    },
    {
      "name": "Lexington",
      "runs": 1,
      "mi": 11,
      "country": "United States",
      "lat": 38.098,
      "lng": -84.4987
    },
    {
      "name": "High Point",
      "runs": 1,
      "mi": 4,
      "country": "United States",
      "lat": 36.0043,
      "lng": -79.9548
    },
    {
      "name": "Shanghai",
      "runs": 1,
      "mi": 9,
      "country": "China",
      "lat": 31.2371,
      "lng": 121.4938
    },
    {
      "name": "Edgmont",
      "runs": 1,
      "mi": 11,
      "country": "United States",
      "lat": 39.9525,
      "lng": -75.447
    },
    {
      "name": "Burke County",
      "runs": 1,
      "mi": 32,
      "country": "United States",
      "lat": 35.7588,
      "lng": -81.9045
    },
    {
      "name": "Asheville",
      "runs": 1,
      "mi": 26,
      "country": "United States",
      "lat": 35.5965,
      "lng": -82.5502
    },
    {
      "name": "Surry County",
      "runs": 1,
      "mi": 10,
      "country": "United States",
      "lat": 36.3404,
      "lng": -80.4607
    },
    {
      "name": "Fort Worth",
      "runs": 1,
      "mi": 8,
      "country": "United States",
      "lat": 32.7248,
      "lng": -97.363
    }
  ],
  "moreCities": 27,
  "usStatesMap": {
    "Colorado": {
      "runs": 1481,
      "mi": 10851
    },
    "North Carolina": {
      "runs": 430,
      "mi": 3314
    },
    "Massachusetts": {
      "runs": 227,
      "mi": 1896
    },
    "California": {
      "runs": 57,
      "mi": 411
    },
    "Delaware": {
      "runs": 7,
      "mi": 58
    },
    "New York": {
      "runs": 4,
      "mi": 39
    },
    "Maryland": {
      "runs": 5,
      "mi": 32
    },
    "Illinois": {
      "runs": 3,
      "mi": 28
    },
    "Michigan": {
      "runs": 3,
      "mi": 26
    },
    "Missouri": {
      "runs": 2,
      "mi": 20
    },
    "Rhode Island": {
      "runs": 2,
      "mi": 19
    },
    "Pennsylvania": {
      "runs": 2,
      "mi": 17
    },
    "Tennessee": {
      "runs": 3,
      "mi": 17
    },
    "Kentucky": {
      "runs": 1,
      "mi": 11
    },
    "Virginia": {
      "runs": 1,
      "mi": 9
    },
    "Texas": {
      "runs": 1,
      "mi": 8
    },
    "New Mexico": {
      "runs": 1,
      "mi": 7
    }
  },
  "usStates": [
    {
      "name": "Colorado",
      "runs": 1481,
      "mi": 10851,
      "cities": "Denver, Littleton, Sheridan, Cherry Hills Village, Aurora"
    },
    {
      "name": "North Carolina",
      "runs": 430,
      "mi": 3314,
      "cities": "Winston-Salem, Burke County, Asheville, Surry County, High Point"
    },
    {
      "name": "Massachusetts",
      "runs": 227,
      "mi": 1896,
      "cities": "Cambridge, Boston"
    },
    {
      "name": "California",
      "runs": 57,
      "mi": 411,
      "cities": "Altadena/Pasadena, El Cerrito, San Francisco, San Diego, Garden Grove"
    },
    {
      "name": "Delaware",
      "runs": 7,
      "mi": 58,
      "cities": "Camden-Wyoming"
    },
    {
      "name": "New York",
      "runs": 4,
      "mi": 39,
      "cities": "New York, Troy"
    },
    {
      "name": "Maryland",
      "runs": 5,
      "mi": 32,
      "cities": "Ocean City, Annapolis"
    },
    {
      "name": "Illinois",
      "runs": 3,
      "mi": 28,
      "cities": "Chicago"
    },
    {
      "name": "Michigan",
      "runs": 3,
      "mi": 26,
      "cities": "Ann Arbor"
    },
    {
      "name": "Missouri",
      "runs": 2,
      "mi": 20,
      "cities": "St Louis"
    },
    {
      "name": "Rhode Island",
      "runs": 2,
      "mi": 19,
      "cities": "Sachuest Point"
    },
    {
      "name": "Pennsylvania",
      "runs": 2,
      "mi": 17,
      "cities": "Edgmont, Pottstown"
    },
    {
      "name": "Tennessee",
      "runs": 3,
      "mi": 17,
      "cities": "Nashville"
    },
    {
      "name": "Kentucky",
      "runs": 1,
      "mi": 11,
      "cities": "Lexington"
    },
    {
      "name": "Virginia",
      "runs": 1,
      "mi": 9,
      "cities": "Fredericksburg"
    },
    {
      "name": "Texas",
      "runs": 1,
      "mi": 8,
      "cities": "Fort Worth"
    },
    {
      "name": "New Mexico",
      "runs": 1,
      "mi": 7,
      "cities": "Albuquerque"
    }
  ],
  "longest": [
    {
      "date": "2025-10-25",
      "name": "Fonta Flora 50K",
      "mi": 32.4,
      "pace": "8:54"
    },
    {
      "date": "2026-01-03",
      "name": "Frosty 50 2026",
      "mi": 31.4,
      "pace": "7:39"
    },
    {
      "date": "2026-03-21",
      "name": "Asheville Marathon",
      "mi": 26.3,
      "pace": "6:49"
    },
    {
      "date": "2025-12-14",
      "name": "Long run",
      "mi": 21.0,
      "pace": "7:38"
    },
    {
      "date": "2025-11-23",
      "name": "Long run",
      "mi": 21.0,
      "pace": "7:36"
    },
    {
      "date": "2026-03-01",
      "name": "Long run",
      "mi": 21.0,
      "pace": "6:53"
    }
  ],
  "fastest": [
    {
      "date": "2024-10-23",
      "mi": 4.0,
      "pace": "5:28"
    },
    {
      "date": "2026-03-04",
      "mi": 4.0,
      "pace": "5:30"
    },
    {
      "date": "2024-09-04",
      "mi": 4.0,
      "pace": "5:31"
    },
    {
      "date": "2024-10-16",
      "mi": 4.0,
      "pace": "5:34"
    },
    {
      "date": "2020-08-31",
      "mi": 3.1,
      "pace": "5:34"
    },
    {
      "date": "2024-10-30",
      "mi": 4.0,
      "pace": "5:34"
    }
  ],
  "countries": [
    {
      "name": "United States",
      "runs": 2230,
      "mi": 16763,
      "detail": "17 states, 35 cities"
    },
    {
      "name": "Canada",
      "runs": 7,
      "mi": 60,
      "detail": "Vancouver, Toronto, Niagara Falls"
    },
    {
      "name": "Ireland",
      "runs": 5,
      "mi": 43,
      "detail": "Dublin, Galway"
    },
    {
      "name": "China",
      "runs": 3,
      "mi": 20,
      "detail": "Suzhou, Shanghai"
    }
  ],
  "training": {
    "asheville": [
      {
        "w": "-6",
        "r": 5,
        "mi": 49
      },
      {
        "w": "-5",
        "r": 7,
        "mi": 25
      },
      {
        "w": "-4",
        "r": 7,
        "mi": 48
      },
      {
        "w": "-3",
        "r": 7,
        "mi": 50
      },
      {
        "w": "-2",
        "r": 7,
        "mi": 35
      },
      {
        "w": "-1",
        "r": 7,
        "mi": 24
      }
    ],
    "fonta-flora": [
      {
        "w": "-6",
        "r": 5,
        "mi": 48
      },
      {
        "w": "-5",
        "r": 5,
        "mi": 24
      },
      {
        "w": "-4",
        "r": 6,
        "mi": 47
      },
      {
        "w": "-3",
        "r": 6,
        "mi": 50
      },
      {
        "w": "-2",
        "r": 5,
        "mi": 36
      },
      {
        "w": "-1",
        "r": 5,
        "mi": 24
      }
    ],
    "mistletoe": [
      {
        "w": "-6",
        "r": 8,
        "mi": 41
      },
      {
        "w": "-5",
        "r": 7,
        "mi": 41
      },
      {
        "w": "-4",
        "r": 7,
        "mi": 43
      },
      {
        "w": "-3",
        "r": 7,
        "mi": 42
      },
      {
        "w": "-2",
        "r": 3,
        "mi": 20
      },
      {
        "w": "-1",
        "r": 3,
        "mi": 22
      }
    ],
    "salem-lake": [
      {
        "w": "-6",
        "r": 5,
        "mi": 40
      },
      {
        "w": "-5",
        "r": 6,
        "mi": 45
      },
      {
        "w": "-4",
        "r": 5,
        "mi": 44
      },
      {
        "w": "-3",
        "r": 7,
        "mi": 34
      },
      {
        "w": "-2",
        "r": 7,
        "mi": 42
      },
      {
        "w": "-1",
        "r": 5,
        "mi": 37
      }
    ]
  },
  "featuredMetrics": {
    "asheville": {
      "elevGain": 941,
      "elevLoss": 1161,
      "hr": "167 avg / 188 max",
      "cadence": "85 spm",
      "stride": "1.38 m",
      "steps": "30,504",
      "calories": "10,911",
      "te": "5.0 aer / 2.1 anaer",
      "vo2": "65",
      "maxPace": "6:00",
      "hrZones": [
        {
          "z": "Zone 1\u20133",
          "min": 3.9,
          "pct": 2
        },
        {
          "z": "Zone 4",
          "min": 31.3,
          "pct": 17
        },
        {
          "z": "Zone 5",
          "min": 141.1,
          "pct": 79
        },
        {
          "z": "Zone 6",
          "min": 3.1,
          "pct": 2
        }
      ]
    },
    "fonta-flora": {
      "elevGain": 3523,
      "elevLoss": 3505,
      "hr": "157 avg / 176 max",
      "cadence": "81 spm",
      "stride": "1.11 m",
      "steps": "46,886",
      "calories": "15,516",
      "te": "5.0 aerobic",
      "vo2": "66",
      "maxPace": "6:50",
      "hrZones": [
        {
          "z": "Zone 1\u20132",
          "min": 5.2,
          "pct": 2
        },
        {
          "z": "Zone 3",
          "min": 17.6,
          "pct": 6
        },
        {
          "z": "Zone 4",
          "min": 152.6,
          "pct": 53
        },
        {
          "z": "Zone 5",
          "min": 112.8,
          "pct": 39
        }
      ]
    },
    "mistletoe": {
      "elevGain": 492,
      "elevLoss": 488,
      "hr": null,
      "cadence": "88 spm",
      "stride": "1.52 m",
      "steps": "13,938",
      "calories": "5,560",
      "te": "2.2 aerobic",
      "vo2": null,
      "maxPace": "5:12",
      "hrZones": []
    },
    "salem-lake": {
      "elevGain": 1686,
      "elevLoss": 1685,
      "hr": "156 avg / 174 max",
      "cadence": "85 spm",
      "stride": "1.45 m",
      "steps": "20,920",
      "calories": "7,684",
      "te": "5.0 aerobic",
      "vo2": "69",
      "maxPace": "5:24",
      "hrZones": []
    }
  },
  "halfProgression": [
    {
      "date": "2024-12-07",
      "time": "1:18:55",
      "pace": "6:01",
      "loc": "Winston-Salem",
      "pr": true
    },
    {
      "date": "2022-10-30",
      "time": "1:19:01",
      "pace": "6:01",
      "loc": "Cambridge",
      "pr": false
    },
    {
      "date": "2022-10-16",
      "time": "1:19:59",
      "pace": "6:06",
      "loc": "Cambridge",
      "pr": false
    },
    {
      "date": "2022-11-13",
      "time": "1:20:35",
      "pace": "6:05",
      "loc": "Boston",
      "pr": false
    },
    {
      "date": "2021-02-28",
      "time": "1:20:52",
      "pace": "6:12",
      "loc": "Denver",
      "pr": false
    }
  ],
  "span": {
    "start": "2016-12-29",
    "end": "2026-06-20"
  }
};
